// Generated by scheduler/codegen.py
// Device signature: blackhole_12x10
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 12;
constexpr uint32_t GRID_H = 10;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 8;
constexpr uint32_t NUM_PHASE = 1;

// Loaded from scheduler/hardcoded/blackhole_12x10.py.
// packed hardcoded C-write records [phase][y][x]
constexpr uint8_t C_WRITE_hardcoded_packed[1][10][12] = {
    {
        {0x09, 0x19, 0x29, 0x39, 0x49, 0x59, 0x0c, 0x1c, 0x2c, 0x3c, 0x4c, 0x5c},
        {0x69, 0x79, 0x89, 0x99, 0xa9, 0xb9, 0x6c, 0x0d, 0x1d, 0x2d, 0x3d, 0x4d},
        {0xc9, 0xd9, 0xe9, 0x03, 0x13, 0x23, 0x7c, 0x5d, 0x6d, 0x7d, 0x8d, 0x9d},
        {0x3b, 0x4b, 0x5b, 0x6b, 0x7b, 0x8b, 0x8c, 0xad, 0xbd, 0xcd, 0xdd, 0xed},
        {0x9b, 0xab, 0xbb, 0xcb, 0xdb, 0xeb, 0x9c, 0x0f, 0x1f, 0x2f, 0x3f, 0x4f},
        {0x02, 0x12, 0x22, 0x32, 0x42, 0x52, 0xac, 0x5f, 0x6f, 0x7f, 0x8f, 0x9f},
        {0x62, 0x72, 0x82, 0x92, 0xa2, 0xb2, 0xbc, 0xaf, 0xbf, 0xcf, 0xdf, 0xef},
        {0xca, 0xda, 0xea, 0x00, 0x10, 0x20, 0xcc, 0x0e, 0x1e, 0x2e, 0x3e, 0x4e},
        {0x30, 0x40, 0x50, 0x60, 0x70, 0x80, 0xdc, 0x5e, 0x6e, 0x7e, 0x8e, 0x9e},
        {0x90, 0xa0, 0xb0, 0xc0, 0xd0, 0xe0, 0xec, 0xae, 0xbe, 0xce, 0xde, 0xee}
    }
};
constexpr uint32_t C_WRITE_hardcoded_bank_shift = 0;
constexpr uint32_t C_WRITE_hardcoded_bank_mask = 7u;
constexpr uint32_t C_WRITE_hardcoded_noc_shift = 3;
constexpr uint32_t C_WRITE_hardcoded_noc_mask = 1u;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_shift = 4;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_mask = 15u;

FORCE_INLINE uint32_t C_WRITE_hardcoded_packed_at(const uint32_t phase, const uint32_t y, const uint32_t x) {
    return static_cast<uint32_t>(C_WRITE_hardcoded_packed[phase][y][x]);
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_bank(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_bank_shift) & C_WRITE_hardcoded_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_noc(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_noc_shift) & C_WRITE_hardcoded_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_slot_ordinal_shift) & C_WRITE_hardcoded_slot_ordinal_mask;
}
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 15;

#if OPTIMIZED_A_READ
constexpr uint8_t A_MASTER_COL[10] = {0x0b, 0x0a, 0x09, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02};
#else
constexpr uint8_t A_MASTER_COL[10] = {0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b, 0x0b};
#endif

#if OPTIMIZED_B_READ
constexpr uint8_t B_MASTER_ROW[12] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x00, 0x01};
#else
constexpr uint8_t B_MASTER_ROW[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 4;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 5;
// packed A-read transfer records [row][transfer]
constexpr uint8_t A_READ_row_packed[10][4] = {
    {0x05, 0x12, 0x21, 0x41},
    {0x15, 0x25, 0x35, 0x45},
    {0x03, 0x0f, 0x10, 0x1c},
    {0x1b, 0x2b, 0x3b, 0x4b},
    {0x1f, 0x2f, 0x3f, 0x4f},
    {0x09, 0x06, 0x19, 0x39},
    {0x16, 0x26, 0x36, 0x46},
    {0x02, 0x22, 0x32, 0x42},
    {0x04, 0x24, 0x34, 0x44},
    {0x08, 0x28, 0x38, 0x48}
};
constexpr uint32_t A_READ_row_bank_shift = 0;
constexpr uint32_t A_READ_row_bank_mask = 7u;
constexpr uint32_t A_READ_row_noc_shift = 3;
constexpr uint32_t A_READ_row_noc_mask = 1u;
constexpr uint32_t A_READ_row_slot_ordinal_shift = 4;
constexpr uint32_t A_READ_row_slot_ordinal_mask = 7u;

FORCE_INLINE uint32_t A_READ_row_packed_at(const uint32_t y, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(A_READ_row_packed[y][transfer_idx]);
}
FORCE_INLINE uint32_t A_READ_row_bank(const uint32_t packed) {
    return (packed >> A_READ_row_bank_shift) & A_READ_row_bank_mask;
}
FORCE_INLINE uint32_t A_READ_row_noc(const uint32_t packed) {
    return (packed >> A_READ_row_noc_shift) & A_READ_row_noc_mask;
}
FORCE_INLINE uint32_t A_READ_row_slot_ordinal(const uint32_t packed) {
    return (packed >> A_READ_row_slot_ordinal_shift) & A_READ_row_slot_ordinal_mask;
}
constexpr uint32_t B_READ_CHUNKS_PER_CORE = 2;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 3;
// packed B-read transfer records [col][transfer]
constexpr uint8_t B_READ_col_packed[12][2] = {
    {0x09, 0x19},
    {0x2a, 0x25},
    {0x18, 0x17},
    {0x1b, 0x2b},
    {0x0b, 0x27},
    {0x06, 0x14},
    {0x16, 0x26},
    {0x02, 0x12},
    {0x00, 0x0f},
    {0x0c, 0x20},
    {0x21, 0x2c},
    {0x0d, 0x1d}
};
constexpr uint32_t B_READ_col_bank_shift = 0;
constexpr uint32_t B_READ_col_bank_mask = 7u;
constexpr uint32_t B_READ_col_noc_shift = 3;
constexpr uint32_t B_READ_col_noc_mask = 1u;
constexpr uint32_t B_READ_col_slot_ordinal_shift = 4;
constexpr uint32_t B_READ_col_slot_ordinal_mask = 3u;

FORCE_INLINE uint32_t B_READ_col_packed_at(const uint32_t x, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(B_READ_col_packed[x][transfer_idx]);
}
FORCE_INLINE uint32_t B_READ_col_bank(const uint32_t packed) {
    return (packed >> B_READ_col_bank_shift) & B_READ_col_bank_mask;
}
FORCE_INLINE uint32_t B_READ_col_noc(const uint32_t packed) {
    return (packed >> B_READ_col_noc_shift) & B_READ_col_noc_mask;
}
FORCE_INLINE uint32_t B_READ_col_slot_ordinal(const uint32_t packed) {
    return (packed >> B_READ_col_slot_ordinal_shift) & B_READ_col_slot_ordinal_mask;
}
constexpr uint32_t C_WRITE_SCHED_T = 15;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 1;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 15;
// packed generated C-write records [y][x][chunk]
constexpr uint16_t C_WRITE_core_packed[10][12][1] = {
    {
        {0x00d0},
        {0x04a4},
        {0x01f1},
        {0x0767},
        {0x0292},
        {0x0b9b},
        {0x0858},
        {0x0030},
        {0x08f8},
        {0x0ccc},
        {0x02d2},
        {0x05e5}
    },
    {
        {0x0ded},
        {0x0404},
        {0x0bbb},
        {0x0dad},
        {0x07d7},
        {0x0cbc},
        {0x0c9c},
        {0x0838},
        {0x0aba},
        {0x03e3},
        {0x0bfb},
        {0x04e4}
    },
    {
        {0x0939},
        {0x0595},
        {0x0bdb},
        {0x01a1},
        {0x04b4},
        {0x0afa},
        {0x05a5},
        {0x0202},
        {0x0313},
        {0x0dcd},
        {0x0cdc},
        {0x0383}
    },
    {
        {0x09d9},
        {0x0828},
        {0x00f0},
        {0x0979},
        {0x09c9},
        {0x05d5},
        {0x0efe},
        {0x02c2},
        {0x0e6e},
        {0x01d1},
        {0x02b2},
        {0x07a7}
    },
    {
        {0x0868},
        {0x0101},
        {0x03b3},
        {0x0ddd},
        {0x06f6},
        {0x0909},
        {0x0787},
        {0x0aea},
        {0x0e2e},
        {0x05c5},
        {0x0191},
        {0x0d9d}
    },
    {
        {0x0575},
        {0x0606},
        {0x0b4b},
        {0x0cfc},
        {0x06b6},
        {0x02f2},
        {0x0494},
        {0x06d6},
        {0x0cac},
        {0x0ada},
        {0x07b7},
        {0x0a0a}
    },
    {
        {0x0e9e},
        {0x0a9a},
        {0x0c8c},
        {0x0aaa},
        {0x06e6},
        {0x0717},
        {0x0b2b},
        {0x0343},
        {0x0040},
        {0x0080},
        {0x0090},
        {0x08c8}
    },
    {
        {0x03f3},
        {0x0ebe},
        {0x0ede},
        {0x04f4},
        {0x0dfd},
        {0x09a9},
        {0x0cec},
        {0x0646},
        {0x05b5},
        {0x07f7},
        {0x02a2},
        {0x00a0}
    },
    {
        {0x0d0d},
        {0x0444},
        {0x0999},
        {0x0b8b},
        {0x0888},
        {0x09e9},
        {0x06a6},
        {0x01b1},
        {0x01e1},
        {0x0696},
        {0x03a3},
        {0x0818}
    },
    {
        {0x0505},
        {0x0dbd},
        {0x0060},
        {0x0454},
        {0x0beb},
        {0x0e4e},
        {0x0262},
        {0x0e0e},
        {0x0747},
        {0x0a4a},
        {0x0353},
        {0x01c1}
    }
};
constexpr uint32_t C_WRITE_core_time_shift = 0;
constexpr uint32_t C_WRITE_core_time_mask = 15u;
constexpr uint32_t C_WRITE_core_bank_shift = 4;
constexpr uint32_t C_WRITE_core_bank_mask = 7u;
constexpr uint32_t C_WRITE_core_noc_shift = 7;
constexpr uint32_t C_WRITE_core_noc_mask = 1u;
constexpr uint32_t C_WRITE_core_slot_ordinal_shift = 8;
constexpr uint32_t C_WRITE_core_slot_ordinal_mask = 15u;

FORCE_INLINE uint32_t C_WRITE_core_packed_at(const uint32_t y, const uint32_t x, const uint32_t chunk_idx) {
    return static_cast<uint32_t>(C_WRITE_core_packed[y][x][chunk_idx]);
}
FORCE_INLINE uint32_t C_WRITE_core_time(const uint32_t packed) {
    return (packed >> C_WRITE_core_time_shift) & C_WRITE_core_time_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_bank(const uint32_t packed) {
    return (packed >> C_WRITE_core_bank_shift) & C_WRITE_core_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_noc(const uint32_t packed) {
    return (packed >> C_WRITE_core_noc_shift) & C_WRITE_core_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_core_slot_ordinal_shift) & C_WRITE_core_slot_ordinal_mask;
}
