// Generated by scheduler/codegen.py
// Device signature: blackhole_12x1
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 12;
constexpr uint32_t GRID_H = 1;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 8;
constexpr uint32_t NUM_PHASE = 1;

// Loaded from scheduler/hardcoded/blackhole_12x10.py using top-left slice.
// packed hardcoded C-write records [phase][y][x]
constexpr uint8_t C_WRITE_hardcoded_packed[1][1][12] = {
    {
        {0x09, 0x19, 0x29, 0x39, 0x49, 0x59, 0x0c, 0x1c, 0x2c, 0x3c, 0x4c, 0x5c}
    }
};
constexpr uint32_t C_WRITE_hardcoded_bank_shift = 0;
constexpr uint32_t C_WRITE_hardcoded_bank_mask = 7u;
constexpr uint32_t C_WRITE_hardcoded_noc_shift = 3;
constexpr uint32_t C_WRITE_hardcoded_noc_mask = 1u;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_shift = 4;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_mask = 7u;

FORCE_INLINE uint32_t C_WRITE_hardcoded_packed_at(const uint32_t phase, const uint32_t y, const uint32_t x) {
    return static_cast<uint32_t>(C_WRITE_hardcoded_packed[phase][y][x]);
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_bank(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_bank_shift) & C_WRITE_hardcoded_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_noc(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_noc_shift) & C_WRITE_hardcoded_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_slot_ordinal_shift) & C_WRITE_hardcoded_slot_ordinal_mask;
}
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 6;

#if OPTIMIZED_A_READ
constexpr uint8_t A_MASTER_COL[1] = {0x0b};
#else
constexpr uint8_t A_MASTER_COL[1] = {0x0b};
#endif

#if OPTIMIZED_B_READ
constexpr uint8_t B_MASTER_ROW[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#else
constexpr uint8_t B_MASTER_ROW[12] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 8;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 1;
// packed A-read transfer records [row][transfer]
constexpr uint8_t A_READ_row_packed[1][8] = {
    {0x02, 0x0e, 0x00, 0x0c, 0x09, 0x03, 0x05, 0x0f}
};
constexpr uint32_t A_READ_row_bank_shift = 0;
constexpr uint32_t A_READ_row_bank_mask = 7u;
constexpr uint32_t A_READ_row_noc_shift = 3;
constexpr uint32_t A_READ_row_noc_mask = 1u;
constexpr uint32_t A_READ_row_slot_ordinal_shift = 4;
constexpr uint32_t A_READ_row_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t A_READ_row_packed_at(const uint32_t y, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(A_READ_row_packed[y][transfer_idx]);
}
FORCE_INLINE uint32_t A_READ_row_bank(const uint32_t packed) {
    return (packed >> A_READ_row_bank_shift) & A_READ_row_bank_mask;
}
FORCE_INLINE uint32_t A_READ_row_noc(const uint32_t packed) {
    return (packed >> A_READ_row_noc_shift) & A_READ_row_noc_mask;
}
FORCE_INLINE uint32_t A_READ_row_slot_ordinal(const uint32_t packed) {
    return (packed >> A_READ_row_slot_ordinal_shift) & A_READ_row_slot_ordinal_mask;
}
constexpr uint32_t B_READ_CHUNKS_PER_CORE = 2;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 3;
// packed B-read transfer records [col][transfer]
constexpr uint8_t B_READ_col_packed[12][2] = {
    {0x0c, 0x17},
    {0x05, 0x28},
    {0x15, 0x26},
    {0x06, 0x27},
    {0x16, 0x25},
    {0x07, 0x14},
    {0x18, 0x24},
    {0x01, 0x11},
    {0x03, 0x21},
    {0x02, 0x22},
    {0x12, 0x23},
    {0x00, 0x13}
};
constexpr uint32_t B_READ_col_bank_shift = 0;
constexpr uint32_t B_READ_col_bank_mask = 7u;
constexpr uint32_t B_READ_col_noc_shift = 3;
constexpr uint32_t B_READ_col_noc_mask = 1u;
constexpr uint32_t B_READ_col_slot_ordinal_shift = 4;
constexpr uint32_t B_READ_col_slot_ordinal_mask = 3u;

FORCE_INLINE uint32_t B_READ_col_packed_at(const uint32_t x, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(B_READ_col_packed[x][transfer_idx]);
}
FORCE_INLINE uint32_t B_READ_col_bank(const uint32_t packed) {
    return (packed >> B_READ_col_bank_shift) & B_READ_col_bank_mask;
}
FORCE_INLINE uint32_t B_READ_col_noc(const uint32_t packed) {
    return (packed >> B_READ_col_noc_shift) & B_READ_col_noc_mask;
}
FORCE_INLINE uint32_t B_READ_col_slot_ordinal(const uint32_t packed) {
    return (packed >> B_READ_col_slot_ordinal_shift) & B_READ_col_slot_ordinal_mask;
}
constexpr uint32_t C_WRITE_SCHED_T = 3;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 2;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 3;
// packed generated C-write records [y][x][chunk]
constexpr uint8_t C_WRITE_core_packed[1][12][2] = {
    {
        {0x6d, 0xbe},
        {0x28, 0xba},
        {0x79, 0xae},
        {0x24, 0x51},
        {0x65, 0xa6},
        {0x3c, 0x69},
        {0x10, 0xaa},
        {0x00, 0x61},
        {0x2c, 0x92},
        {0x34, 0xa2},
        {0x75, 0xb6},
        {0x38, 0x7d}
    }
};
constexpr uint32_t C_WRITE_core_time_shift = 0;
constexpr uint32_t C_WRITE_core_time_mask = 3u;
constexpr uint32_t C_WRITE_core_bank_shift = 2;
constexpr uint32_t C_WRITE_core_bank_mask = 7u;
constexpr uint32_t C_WRITE_core_noc_shift = 5;
constexpr uint32_t C_WRITE_core_noc_mask = 1u;
constexpr uint32_t C_WRITE_core_slot_ordinal_shift = 6;
constexpr uint32_t C_WRITE_core_slot_ordinal_mask = 3u;

FORCE_INLINE uint32_t C_WRITE_core_packed_at(const uint32_t y, const uint32_t x, const uint32_t chunk_idx) {
    return static_cast<uint32_t>(C_WRITE_core_packed[y][x][chunk_idx]);
}
FORCE_INLINE uint32_t C_WRITE_core_time(const uint32_t packed) {
    return (packed >> C_WRITE_core_time_shift) & C_WRITE_core_time_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_bank(const uint32_t packed) {
    return (packed >> C_WRITE_core_bank_shift) & C_WRITE_core_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_noc(const uint32_t packed) {
    return (packed >> C_WRITE_core_noc_shift) & C_WRITE_core_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_core_slot_ordinal_shift) & C_WRITE_core_slot_ordinal_mask;
}
