// Generated by scheduler/codegen.py
// Device signature: blackhole_1x10
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 1;
constexpr uint32_t GRID_H = 10;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 8;
constexpr uint32_t NUM_PHASE = 1;

// Loaded from scheduler/hardcoded/blackhole_12x10.py using top-left slice.
// packed hardcoded C-write records [phase][y][x]
constexpr uint8_t C_WRITE_hardcoded_packed[1][10][1] = {
    {
        {0x05},
        {0x0d},
        {0x15},
        {0x07},
        {0x0f},
        {0x02},
        {0x0a},
        {0x16},
        {0x00},
        {0x08}
    }
};
constexpr uint32_t C_WRITE_hardcoded_bank_shift = 0;
constexpr uint32_t C_WRITE_hardcoded_bank_mask = 3u;
constexpr uint32_t C_WRITE_hardcoded_noc_shift = 2;
constexpr uint32_t C_WRITE_hardcoded_noc_mask = 1u;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_shift = 3;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_mask = 3u;

FORCE_INLINE uint32_t C_WRITE_hardcoded_packed_at(const uint32_t phase, const uint32_t y, const uint32_t x) {
    return static_cast<uint32_t>(C_WRITE_hardcoded_packed[phase][y][x]);
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_bank(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_bank_shift) & C_WRITE_hardcoded_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_noc(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_noc_shift) & C_WRITE_hardcoded_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_slot_ordinal_shift) & C_WRITE_hardcoded_slot_ordinal_mask;
}
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 3;

#if OPTIMIZED_A_READ
constexpr uint8_t A_MASTER_COL[10] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#else
constexpr uint8_t A_MASTER_COL[10] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#endif

#if OPTIMIZED_B_READ
constexpr uint8_t B_MASTER_ROW[1] = {0x00};
#else
constexpr uint8_t B_MASTER_ROW[1] = {0x00};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 4;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 5;
// packed A-read transfer records [row][transfer]
constexpr uint8_t A_READ_row_packed[10][4] = {
    {0x09, 0x29, 0x39, 0x4b},
    {0x15, 0x2a, 0x35, 0x45},
    {0x0d, 0x1a, 0x2d, 0x38},
    {0x0b, 0x1b, 0x2b, 0x3b},
    {0x0f, 0x27, 0x46, 0x4f},
    {0x08, 0x1f, 0x3f, 0x48},
    {0x0e, 0x1e, 0x26, 0x36},
    {0x0a, 0x24, 0x3a, 0x4a},
    {0x04, 0x19, 0x14, 0x34},
    {0x18, 0x28, 0x49, 0x44}
};
constexpr uint32_t A_READ_row_bank_shift = 0;
constexpr uint32_t A_READ_row_bank_mask = 7u;
constexpr uint32_t A_READ_row_noc_shift = 3;
constexpr uint32_t A_READ_row_noc_mask = 1u;
constexpr uint32_t A_READ_row_slot_ordinal_shift = 4;
constexpr uint32_t A_READ_row_slot_ordinal_mask = 7u;

FORCE_INLINE uint32_t A_READ_row_packed_at(const uint32_t y, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(A_READ_row_packed[y][transfer_idx]);
}
FORCE_INLINE uint32_t A_READ_row_bank(const uint32_t packed) {
    return (packed >> A_READ_row_bank_shift) & A_READ_row_bank_mask;
}
FORCE_INLINE uint32_t A_READ_row_noc(const uint32_t packed) {
    return (packed >> A_READ_row_noc_shift) & A_READ_row_noc_mask;
}
FORCE_INLINE uint32_t A_READ_row_slot_ordinal(const uint32_t packed) {
    return (packed >> A_READ_row_slot_ordinal_shift) & A_READ_row_slot_ordinal_mask;
}
constexpr uint32_t B_READ_CHUNKS_PER_CORE = 8;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 1;
// packed B-read transfer records [col][transfer]
constexpr uint8_t B_READ_col_packed[1][8] = {
    {0x0b, 0x06, 0x0c, 0x07, 0x08, 0x01, 0x0a, 0x05}
};
constexpr uint32_t B_READ_col_bank_shift = 0;
constexpr uint32_t B_READ_col_bank_mask = 7u;
constexpr uint32_t B_READ_col_noc_shift = 3;
constexpr uint32_t B_READ_col_noc_mask = 1u;
constexpr uint32_t B_READ_col_slot_ordinal_shift = 4;
constexpr uint32_t B_READ_col_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t B_READ_col_packed_at(const uint32_t x, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(B_READ_col_packed[x][transfer_idx]);
}
FORCE_INLINE uint32_t B_READ_col_bank(const uint32_t packed) {
    return (packed >> B_READ_col_bank_shift) & B_READ_col_bank_mask;
}
FORCE_INLINE uint32_t B_READ_col_noc(const uint32_t packed) {
    return (packed >> B_READ_col_noc_shift) & B_READ_col_noc_mask;
}
FORCE_INLINE uint32_t B_READ_col_slot_ordinal(const uint32_t packed) {
    return (packed >> B_READ_col_slot_ordinal_shift) & B_READ_col_slot_ordinal_mask;
}
constexpr uint32_t C_WRITE_SCHED_T = 5;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 4;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 5;
// packed generated C-write records [y][x][chunk]
constexpr uint16_t C_WRITE_core_packed[10][1][4] = {
    {
        {0x00c9, 0x014a, 0x01cb, 0x024c}
    },
    {
        {0x0038, 0x00b9, 0x016a, 0x01eb}
    },
    {
        {0x0018, 0x00e9, 0x011a, 0x019b}
    },
    {
        {0x0081, 0x0102, 0x0183, 0x026c}
    },
    {
        {0x0020, 0x00a1, 0x017a, 0x0224}
    },
    {
        {0x0048, 0x0152, 0x01d3, 0x025c}
    },
    {
        {0x0000, 0x00d9, 0x0122, 0x0214}
    },
    {
        {0x0050, 0x00f1, 0x01f3, 0x0204}
    },
    {
        {0x0070, 0x00d1, 0x01a3, 0x0274}
    },
    {
        {0x0028, 0x0132, 0x01bb, 0x023c}
    }
};
constexpr uint32_t C_WRITE_core_time_shift = 0;
constexpr uint32_t C_WRITE_core_time_mask = 7u;
constexpr uint32_t C_WRITE_core_bank_shift = 3;
constexpr uint32_t C_WRITE_core_bank_mask = 7u;
constexpr uint32_t C_WRITE_core_noc_shift = 6;
constexpr uint32_t C_WRITE_core_noc_mask = 1u;
constexpr uint32_t C_WRITE_core_slot_ordinal_shift = 7;
constexpr uint32_t C_WRITE_core_slot_ordinal_mask = 7u;

FORCE_INLINE uint32_t C_WRITE_core_packed_at(const uint32_t y, const uint32_t x, const uint32_t chunk_idx) {
    return static_cast<uint32_t>(C_WRITE_core_packed[y][x][chunk_idx]);
}
FORCE_INLINE uint32_t C_WRITE_core_time(const uint32_t packed) {
    return (packed >> C_WRITE_core_time_shift) & C_WRITE_core_time_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_bank(const uint32_t packed) {
    return (packed >> C_WRITE_core_bank_shift) & C_WRITE_core_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_noc(const uint32_t packed) {
    return (packed >> C_WRITE_core_noc_shift) & C_WRITE_core_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_core_slot_ordinal_shift) & C_WRITE_core_slot_ordinal_mask;
}
