// Generated by scheduler/codegen.py
// Device signature: wormhole_b0_8x1_0
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 8;
constexpr uint32_t GRID_H = 1;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 12;
constexpr uint32_t NUM_PHASE = 3;

// Loaded from scheduler/hardcoded/wormhole_b0_8x8_0.py using top-left slice.
// packed hardcoded C-write records [phase][y][x]
constexpr uint8_t C_WRITE_hardcoded_packed[3][1][8] = {
    {
        {0x09, 0x08, 0x04, 0x14, 0x24, 0x34, 0x44, 0x54}
    },
    {
        {0x19, 0x18, 0x64, 0x28, 0x74, 0x84, 0x94, 0xa4}
    },
    {
        {0x29, 0x38, 0xb4, 0x48, 0xc4, 0xd4, 0xe4, 0xf4}
    }
};
constexpr uint32_t C_WRITE_hardcoded_bank_shift = 0;
constexpr uint32_t C_WRITE_hardcoded_bank_mask = 7u;
constexpr uint32_t C_WRITE_hardcoded_noc_shift = 3;
constexpr uint32_t C_WRITE_hardcoded_noc_mask = 1u;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_shift = 4;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_mask = 15u;

FORCE_INLINE uint32_t C_WRITE_hardcoded_packed_at(const uint32_t phase, const uint32_t y, const uint32_t x) {
    return static_cast<uint32_t>(C_WRITE_hardcoded_packed[phase][y][x]);
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_bank(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_bank_shift) & C_WRITE_hardcoded_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_noc(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_noc_shift) & C_WRITE_hardcoded_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_slot_ordinal_shift) & C_WRITE_hardcoded_slot_ordinal_mask;
}
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 16;

#if OPTIMIZED_A_READ
constexpr uint8_t A_MASTER_COL[1] = {0x07};
#else
constexpr uint8_t A_MASTER_COL[1] = {0x07};
#endif

#if OPTIMIZED_B_READ
constexpr uint8_t B_MASTER_ROW[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#else
constexpr uint8_t B_MASTER_ROW[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 12;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 1;
// packed A-read transfer records [row][transfer]
constexpr uint8_t A_READ_row_packed[1][12] = {
    {0x01, 0x1b, 0x18, 0x0a, 0x10, 0x02, 0x14, 0x09, 0x06, 0x17, 0x03, 0x15}
};
constexpr uint32_t A_READ_row_bank_shift = 0;
constexpr uint32_t A_READ_row_bank_mask = 15u;
constexpr uint32_t A_READ_row_noc_shift = 4;
constexpr uint32_t A_READ_row_noc_mask = 1u;
constexpr uint32_t A_READ_row_slot_ordinal_shift = 5;
constexpr uint32_t A_READ_row_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t A_READ_row_packed_at(const uint32_t y, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(A_READ_row_packed[y][transfer_idx]);
}
FORCE_INLINE uint32_t A_READ_row_bank(const uint32_t packed) {
    return (packed >> A_READ_row_bank_shift) & A_READ_row_bank_mask;
}
FORCE_INLINE uint32_t A_READ_row_noc(const uint32_t packed) {
    return (packed >> A_READ_row_noc_shift) & A_READ_row_noc_mask;
}
FORCE_INLINE uint32_t A_READ_row_slot_ordinal(const uint32_t packed) {
    return (packed >> A_READ_row_slot_ordinal_shift) & A_READ_row_slot_ordinal_mask;
}
constexpr uint32_t B_READ_CHUNKS_PER_CORE = 3;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 2;
// packed B-read transfer records [col][transfer]
constexpr uint8_t B_READ_col_packed[8][3] = {
    {0x04, 0x0b, 0x21},
    {0x08, 0x01, 0x26},
    {0x15, 0x35, 0x28},
    {0x07, 0x27, 0x22},
    {0x03, 0x06, 0x23},
    {0x09, 0x02, 0x24},
    {0x10, 0x30, 0x29},
    {0x0a, 0x2a, 0x3b}
};
constexpr uint32_t B_READ_col_bank_shift = 0;
constexpr uint32_t B_READ_col_bank_mask = 15u;
constexpr uint32_t B_READ_col_noc_shift = 4;
constexpr uint32_t B_READ_col_noc_mask = 1u;
constexpr uint32_t B_READ_col_slot_ordinal_shift = 5;
constexpr uint32_t B_READ_col_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t B_READ_col_packed_at(const uint32_t x, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(B_READ_col_packed[x][transfer_idx]);
}
FORCE_INLINE uint32_t B_READ_col_bank(const uint32_t packed) {
    return (packed >> B_READ_col_bank_shift) & B_READ_col_bank_mask;
}
FORCE_INLINE uint32_t B_READ_col_noc(const uint32_t packed) {
    return (packed >> B_READ_col_noc_shift) & B_READ_col_noc_mask;
}
FORCE_INLINE uint32_t B_READ_col_slot_ordinal(const uint32_t packed) {
    return (packed >> B_READ_col_slot_ordinal_shift) & B_READ_col_slot_ordinal_mask;
}
constexpr uint32_t C_WRITE_SCHED_T = 3;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 3;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 2;
// packed generated C-write records [y][x][chunk]
constexpr uint8_t C_WRITE_core_packed[1][8][3] = {
    {
        {0x10, 0x49, 0xce},
        {0x60, 0x5d, 0xca},
        {0x44, 0xad, 0x96},
        {0x54, 0xc1, 0xe6},
        {0x00, 0xd9, 0xe2},
        {0x6c, 0x4d, 0xd2},
        {0x58, 0x65, 0xea},
        {0x68, 0xc5, 0xde}
    }
};
constexpr uint32_t C_WRITE_core_time_shift = 0;
constexpr uint32_t C_WRITE_core_time_mask = 3u;
constexpr uint32_t C_WRITE_core_bank_shift = 2;
constexpr uint32_t C_WRITE_core_bank_mask = 15u;
constexpr uint32_t C_WRITE_core_noc_shift = 6;
constexpr uint32_t C_WRITE_core_noc_mask = 1u;
constexpr uint32_t C_WRITE_core_slot_ordinal_shift = 7;
constexpr uint32_t C_WRITE_core_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t C_WRITE_core_packed_at(const uint32_t y, const uint32_t x, const uint32_t chunk_idx) {
    return static_cast<uint32_t>(C_WRITE_core_packed[y][x][chunk_idx]);
}
FORCE_INLINE uint32_t C_WRITE_core_time(const uint32_t packed) {
    return (packed >> C_WRITE_core_time_shift) & C_WRITE_core_time_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_bank(const uint32_t packed) {
    return (packed >> C_WRITE_core_bank_shift) & C_WRITE_core_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_noc(const uint32_t packed) {
    return (packed >> C_WRITE_core_noc_shift) & C_WRITE_core_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_core_slot_ordinal_shift) & C_WRITE_core_slot_ordinal_mask;
}
