// Generated by scheduler/codegen.py
// Device signature: wormhole_b0_1x8
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 1;
constexpr uint32_t GRID_H = 8;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 12;
constexpr uint32_t NUM_PHASE = 3;

// Loaded from scheduler/hardcoded/wormhole_b0_8x8.py using top-left slice.
constexpr uint8_t C_WRITE_NOC[3][8][1] = {
    {
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1}
    },
    {
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1}
    },
    {
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1},
        {1}
    }
};

// Loaded from scheduler/hardcoded/wormhole_b0_8x8.py using top-left slice.
constexpr uint8_t C_WRITE_BANK[3][8][1] = {
    {
        {1},
        {1},
        {1},
        {1},
        {2},
        {2},
        {3},
        {3}
    },
    {
        {1},
        {1},
        {1},
        {1},
        {2},
        {2},
        {3},
        {3}
    },
    {
        {1},
        {1},
        {1},
        {1},
        {2},
        {2},
        {3},
        {3}
    }
};

// bank-local valid slot ordinal for the hardcoded phase table
constexpr uint8_t C_WRITE_HARDCODED_slot_ordinal[3][8][1] = {
    {
        {0},
        {1},
        {2},
        {3},
        {0},
        {1},
        {0},
        {1}
    },
    {
        {4},
        {5},
        {6},
        {7},
        {2},
        {3},
        {2},
        {3}
    },
    {
        {8},
        {9},
        {10},
        {11},
        {4},
        {5},
        {4},
        {5}
    }
};
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 12;

#if OPTIMIZED_A_READ
constexpr uint32_t A_MASTER_COL[8] = {0, 0, 0, 0, 0, 0, 0, 0};
#else
constexpr uint32_t A_MASTER_COL[8] = {0, 0, 0, 0, 0, 0, 0, 0};
#endif

#if OPTIMIZED_B_READ
constexpr uint32_t B_MASTER_ROW[1] = {0};
#else
constexpr uint32_t B_MASTER_ROW[1] = {0};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 3;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 2;
// core-major compact bank list
constexpr uint8_t A_READ_core_bank[8][1][3] = {
    {
        {1, 4, 1}
    },
    {
        {6, 5, 6}
    },
    {
        {5, 9, 9}
    },
    {
        {0, 2, 3}
    },
    {
        {10, 2, 10}
    },
    {
        {3, 11, 11}
    },
    {
        {8, 0, 8}
    },
    {
        {7, 4, 7}
    }
};
// core-major compact NoC list
constexpr uint8_t A_READ_core_noc[8][1][3] = {
    {
        {1, 0, 1}
    },
    {
        {0, 1, 0}
    },
    {
        {1, 0, 0}
    },
    {
        {1, 0, 1}
    },
    {
        {1, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {1, 1, 0}
    },
    {
        {0, 0, 1}
    }
};
// core-major compact slot ordinal list
constexpr uint8_t A_READ_core_slot_ordinal[8][1][3] = {
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 1, 1}
    }
};

constexpr uint32_t B_READ_CHUNKS_PER_CORE = 12;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 1;
// core-major compact bank list
constexpr uint8_t B_READ_core_bank[8][1][12] = {
    {
        {1, 11, 5, 8, 3, 10, 2, 4, 6, 7, 0, 9}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    }
};
// core-major compact NoC list
constexpr uint8_t B_READ_core_noc[8][1][12] = {
    {
        {1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    }
};
// core-major compact slot ordinal list
constexpr uint8_t B_READ_core_slot_ordinal[8][1][12] = {
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    }
};

constexpr uint32_t C_WRITE_SCHED_T = 3;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 3;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 2;
// generated C-write sparse per-core event times [y][x][chunk]
constexpr uint8_t C_WRITE_core_time[8][1][3] = {
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    },
    {
        {0, 1, 2}
    }
};
// generated C-write sparse per-core bank list [y][x][chunk]
constexpr uint8_t C_WRITE_core_bank[8][1][3] = {
    {
        {0, 0, 5}
    },
    {
        {8, 4, 10}
    },
    {
        {9, 8, 6}
    },
    {
        {10, 2, 1}
    },
    {
        {11, 9, 11}
    },
    {
        {3, 1, 2}
    },
    {
        {6, 7, 4}
    },
    {
        {7, 5, 3}
    }
};
// generated C-write sparse per-core NoC list [y][x][chunk]
constexpr uint8_t C_WRITE_core_noc[8][1][3] = {
    {
        {0, 1, 1}
    },
    {
        {1, 1, 0}
    },
    {
        {1, 0, 1}
    },
    {
        {0, 0, 0}
    },
    {
        {0, 1, 0}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 0, 0}
    },
    {
        {1, 0, 1}
    }
};
// generated C-write sparse per-core slot ordinals [y][x][chunk]
constexpr uint8_t C_WRITE_core_slot_ordinal[8][1][3] = {
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    },
    {
        {0, 1, 1}
    },
    {
        {0, 0, 1}
    }
};
