// Generated by scheduler/codegen.py
// Device signature: wormhole_b0_8x1
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 8;
constexpr uint32_t GRID_H = 1;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 12;
constexpr uint32_t NUM_PHASE = 3;

// Loaded from scheduler/hardcoded/wormhole_b0_8x8.py using top-left slice.
constexpr uint8_t C_WRITE_NOC[3][1][8] = {
    {
        {1, 1, 0, 0, 0, 0, 0, 0}
    },
    {
        {1, 1, 0, 1, 0, 0, 0, 0}
    },
    {
        {1, 1, 0, 1, 0, 0, 0, 0}
    }
};

// Loaded from scheduler/hardcoded/wormhole_b0_8x8.py using top-left slice.
constexpr uint8_t C_WRITE_BANK[3][1][8] = {
    {
        {1, 0, 4, 4, 4, 4, 4, 4}
    },
    {
        {1, 0, 4, 0, 4, 4, 4, 4}
    },
    {
        {1, 0, 4, 0, 4, 4, 4, 4}
    }
};

// bank-local valid slot ordinal for the hardcoded phase table
constexpr uint8_t C_WRITE_HARDCODED_slot_ordinal[3][1][8] = {
    {
        {0, 0, 0, 1, 2, 3, 4, 5}
    },
    {
        {1, 1, 6, 2, 7, 8, 9, 10}
    },
    {
        {2, 3, 11, 4, 12, 13, 14, 15}
    }
};
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 16;

#if OPTIMIZED_A_READ
constexpr uint32_t A_MASTER_COL[1] = {7};
#else
constexpr uint32_t A_MASTER_COL[1] = {7};
#endif

#if OPTIMIZED_B_READ
constexpr uint32_t B_MASTER_ROW[8] = {0, 0, 0, 0, 0, 0, 0, 0};
#else
constexpr uint32_t B_MASTER_ROW[8] = {0, 0, 0, 0, 0, 0, 0, 0};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 12;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 1;
// core-major compact bank list
constexpr uint8_t A_READ_core_bank[1][8][12] = {
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {1, 11, 8, 10, 0, 2, 4, 9, 6, 7, 3, 5}
    }
};
// core-major compact NoC list
constexpr uint8_t A_READ_core_noc[1][8][12] = {
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1}
    }
};
// core-major compact slot ordinal list
constexpr uint8_t A_READ_core_slot_ordinal[1][8][12] = {
    {
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    }
};

constexpr uint32_t B_READ_CHUNKS_PER_CORE = 3;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 2;
// core-major compact bank list
constexpr uint8_t B_READ_core_bank[1][8][3] = {
    {
        {1, 4, 1},
        {10, 8, 11},
        {8, 5, 5},
        {7, 7, 2},
        {3, 0, 3},
        {9, 2, 4},
        {6, 0, 9},
        {11, 6, 10}
    }
};
// core-major compact NoC list
constexpr uint8_t B_READ_core_noc[1][8][3] = {
    {
        {0, 0, 0},
        {0, 0, 0},
        {0, 1, 1},
        {0, 0, 0},
        {0, 1, 0},
        {0, 0, 0},
        {0, 1, 0},
        {1, 0, 0}
    }
};
// core-major compact slot ordinal list
constexpr uint8_t B_READ_core_slot_ordinal[1][8][3] = {
    {
        {0, 0, 1},
        {0, 1, 1},
        {0, 0, 1},
        {0, 1, 1},
        {0, 0, 1},
        {0, 0, 1},
        {0, 1, 1},
        {0, 1, 1}
    }
};

constexpr uint32_t C_WRITE_SCHED_T = 3;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 3;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 2;
// generated C-write sparse per-core event times [y][x][chunk]
constexpr uint8_t C_WRITE_core_time[1][8][3] = {
    {
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2},
        {0, 1, 2}
    }
};
// generated C-write sparse per-core bank list [y][x][chunk]
constexpr uint8_t C_WRITE_core_bank[1][8][3] = {
    {
        {4, 2, 3},
        {8, 7, 2},
        {1, 11, 5},
        {5, 0, 9},
        {0, 6, 8},
        {11, 3, 4},
        {6, 9, 10},
        {10, 1, 7}
    }
};
// generated C-write sparse per-core NoC list [y][x][chunk]
constexpr uint8_t C_WRITE_core_noc[1][8][3] = {
    {
        {0, 1, 1},
        {1, 1, 1},
        {1, 0, 0},
        {1, 1, 1},
        {0, 1, 1},
        {1, 1, 1},
        {1, 1, 1},
        {1, 1, 1}
    }
};
// generated C-write sparse per-core slot ordinals [y][x][chunk]
constexpr uint8_t C_WRITE_core_slot_ordinal[1][8][3] = {
    {
        {0, 0, 1},
        {0, 0, 1},
        {0, 1, 1},
        {0, 1, 1},
        {0, 1, 1},
        {0, 0, 1},
        {0, 0, 1},
        {0, 1, 1}
    }
};
