// Generated by scheduler/codegen.py
// Device signature: wormhole_b0_8x8_5
#pragma once

#include <cstdint>

constexpr uint32_t GRID_W = 8;
constexpr uint32_t GRID_H = 8;
constexpr uint32_t GRID_START = 0;
constexpr uint32_t GRID_END_X = GRID_W - 1;
constexpr uint32_t GRID_END_Y = GRID_H - 1;
constexpr uint32_t DRAM_BANK_COUNT = 12;
constexpr uint32_t NUM_PHASE = 3;

// Loaded from scheduler/hardcoded/wormhole_b0_8x8_5.py.
// packed hardcoded C-write records [phase][y][x]
constexpr uint16_t C_WRITE_hardcoded_packed[3][8][8] = {
    {
        {0x0010, 0x0030, 0x0006, 0x0026, 0x0046, 0x0066, 0x0086, 0x00a6},
        {0x0011, 0x0031, 0x0019, 0x0039, 0x0059, 0x0079, 0x0099, 0x00b9},
        {0x0051, 0x0071, 0x000a, 0x002a, 0x004a, 0x006a, 0x008a, 0x00aa},
        {0x0013, 0x0012, 0x000b, 0x002b, 0x004b, 0x006b, 0x008b, 0x00ab},
        {0x0033, 0x0032, 0x0008, 0x0028, 0x0048, 0x0068, 0x0088, 0x00a8},
        {0x0053, 0x0052, 0x0007, 0x0027, 0x0047, 0x0067, 0x0087, 0x00a7},
        {0x0073, 0x0072, 0x0005, 0x0025, 0x0045, 0x0065, 0x0085, 0x00a5},
        {0x0050, 0x0070, 0x0004, 0x0024, 0x0044, 0x0064, 0x0084, 0x00a4}
    },
    {
        {0x0090, 0x00b0, 0x00d0, 0x00c6, 0x00e6, 0x0106, 0x0126, 0x0146},
        {0x0091, 0x00b1, 0x00d1, 0x00d9, 0x00f9, 0x0119, 0x0139, 0x0159},
        {0x00f1, 0x0111, 0x0131, 0x00ca, 0x00ea, 0x010a, 0x012a, 0x014a},
        {0x0093, 0x0092, 0x00cb, 0x00b2, 0x00eb, 0x010b, 0x012b, 0x014b},
        {0x00b3, 0x00d2, 0x00c8, 0x00f2, 0x00e8, 0x0108, 0x0128, 0x0148},
        {0x00d3, 0x0112, 0x00f3, 0x00c7, 0x00e7, 0x0107, 0x0127, 0x0147},
        {0x0113, 0x0132, 0x0133, 0x00c5, 0x00e5, 0x0105, 0x0125, 0x0145},
        {0x00f0, 0x0110, 0x0130, 0x00c4, 0x00e4, 0x0104, 0x0124, 0x0144}
    },
    {
        {0x0150, 0x0170, 0x0190, 0x0166, 0x0186, 0x01a6, 0x01c6, 0x01e6},
        {0x0151, 0x0171, 0x0191, 0x0179, 0x0199, 0x01b9, 0x01d9, 0x01f9},
        {0x01b1, 0x01d1, 0x01f1, 0x016a, 0x018a, 0x01aa, 0x01ca, 0x01ea},
        {0x0153, 0x0152, 0x016b, 0x0172, 0x018b, 0x01ab, 0x01cb, 0x01eb},
        {0x0173, 0x0192, 0x0168, 0x01b2, 0x0188, 0x01a8, 0x01c8, 0x01e8},
        {0x0193, 0x01d2, 0x01b3, 0x0167, 0x0187, 0x01a7, 0x01c7, 0x01e7},
        {0x01d3, 0x01f2, 0x01f3, 0x0165, 0x0185, 0x01a5, 0x01c5, 0x01e5},
        {0x01b0, 0x01d0, 0x01f0, 0x0164, 0x0184, 0x01a4, 0x01c4, 0x01e4}
    }
};
constexpr uint32_t C_WRITE_hardcoded_bank_shift = 0;
constexpr uint32_t C_WRITE_hardcoded_bank_mask = 15u;
constexpr uint32_t C_WRITE_hardcoded_noc_shift = 4;
constexpr uint32_t C_WRITE_hardcoded_noc_mask = 1u;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_shift = 5;
constexpr uint32_t C_WRITE_hardcoded_slot_ordinal_mask = 15u;

FORCE_INLINE uint32_t C_WRITE_hardcoded_packed_at(const uint32_t phase, const uint32_t y, const uint32_t x) {
    return static_cast<uint32_t>(C_WRITE_hardcoded_packed[phase][y][x]);
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_bank(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_bank_shift) & C_WRITE_hardcoded_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_noc(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_noc_shift) & C_WRITE_hardcoded_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_hardcoded_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_hardcoded_slot_ordinal_shift) & C_WRITE_hardcoded_slot_ordinal_mask;
}
constexpr uint8_t C_WRITE_HARDCODED_valid_slots_per_bank_count = 16;

#if OPTIMIZED_A_READ
constexpr uint8_t A_MASTER_COL[8] = {0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00};
#else
constexpr uint8_t A_MASTER_COL[8] = {0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07};
#endif

#if OPTIMIZED_B_READ
constexpr uint8_t B_MASTER_ROW[8] = {0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07};
#else
constexpr uint8_t B_MASTER_ROW[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
#endif

constexpr uint32_t A_READ_CHUNKS_PER_CORE = 3;
constexpr uint8_t A_READ_valid_slots_per_bank_count = 2;
// packed A-read transfer records [row][transfer]
constexpr uint8_t A_READ_row_packed[8][3] = {
    {0x01, 0x14, 0x21},
    {0x0a, 0x34, 0x2a},
    {0x12, 0x03, 0x32},
    {0x1b, 0x20, 0x3b},
    {0x08, 0x33, 0x28},
    {0x09, 0x37, 0x29},
    {0x06, 0x17, 0x26},
    {0x10, 0x05, 0x35}
};
constexpr uint32_t A_READ_row_bank_shift = 0;
constexpr uint32_t A_READ_row_bank_mask = 15u;
constexpr uint32_t A_READ_row_noc_shift = 4;
constexpr uint32_t A_READ_row_noc_mask = 1u;
constexpr uint32_t A_READ_row_slot_ordinal_shift = 5;
constexpr uint32_t A_READ_row_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t A_READ_row_packed_at(const uint32_t y, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(A_READ_row_packed[y][transfer_idx]);
}
FORCE_INLINE uint32_t A_READ_row_bank(const uint32_t packed) {
    return (packed >> A_READ_row_bank_shift) & A_READ_row_bank_mask;
}
FORCE_INLINE uint32_t A_READ_row_noc(const uint32_t packed) {
    return (packed >> A_READ_row_noc_shift) & A_READ_row_noc_mask;
}
FORCE_INLINE uint32_t A_READ_row_slot_ordinal(const uint32_t packed) {
    return (packed >> A_READ_row_slot_ordinal_shift) & A_READ_row_slot_ordinal_mask;
}
constexpr uint32_t B_READ_CHUNKS_PER_CORE = 3;
constexpr uint8_t B_READ_valid_slots_per_bank_count = 2;
// packed B-read transfer records [col][transfer]
constexpr uint8_t B_READ_col_packed[8][3] = {
    {0x14, 0x09, 0x34},
    {0x10, 0x39, 0x2b},
    {0x1a, 0x28, 0x3a},
    {0x13, 0x06, 0x26},
    {0x18, 0x20, 0x33},
    {0x01, 0x17, 0x27},
    {0x05, 0x1b, 0x21},
    {0x02, 0x22, 0x35}
};
constexpr uint32_t B_READ_col_bank_shift = 0;
constexpr uint32_t B_READ_col_bank_mask = 15u;
constexpr uint32_t B_READ_col_noc_shift = 4;
constexpr uint32_t B_READ_col_noc_mask = 1u;
constexpr uint32_t B_READ_col_slot_ordinal_shift = 5;
constexpr uint32_t B_READ_col_slot_ordinal_mask = 1u;

FORCE_INLINE uint32_t B_READ_col_packed_at(const uint32_t x, const uint32_t transfer_idx) {
    return static_cast<uint32_t>(B_READ_col_packed[x][transfer_idx]);
}
FORCE_INLINE uint32_t B_READ_col_bank(const uint32_t packed) {
    return (packed >> B_READ_col_bank_shift) & B_READ_col_bank_mask;
}
FORCE_INLINE uint32_t B_READ_col_noc(const uint32_t packed) {
    return (packed >> B_READ_col_noc_shift) & B_READ_col_noc_mask;
}
FORCE_INLINE uint32_t B_READ_col_slot_ordinal(const uint32_t packed) {
    return (packed >> B_READ_col_slot_ordinal_shift) & B_READ_col_slot_ordinal_mask;
}
constexpr uint32_t C_WRITE_SCHED_T = 16;
constexpr uint32_t C_WRITE_CHUNKS_PER_CORE = 3;
constexpr uint8_t C_WRITE_valid_slots_per_bank_count = 16;
// packed generated C-write records [y][x][chunk]
constexpr uint16_t C_WRITE_core_packed[8][8][3] = {
    {
        {0x0381, 0x176b, 0x1dae},
        {0x0040, 0x0b25, 0x196c},
        {0x0180, 0x1389, 0x1e3f},
        {0x0eb7, 0x177b, 0x1c4e},
        {0x0d86, 0x13b9, 0x158a},
        {0x0954, 0x1b7d, 0x1d1e},
        {0x0613, 0x155a, 0x19ac},
        {0x0c26, 0x0f47, 0x1198}
    },
    {
        {0x0743, 0x0904, 0x0f27},
        {0x0a55, 0x142a, 0x1b9d},
        {0x0190, 0x06a3, 0x195c},
        {0x05b2, 0x0793, 0x0934},
        {0x0221, 0x0824, 0x1078},
        {0x0d56, 0x178b, 0x1d8e},
        {0x00b0, 0x0b95, 0x1f4f},
        {0x0422, 0x0964, 0x181c}
    },
    {
        {0x0492, 0x1118, 0x1f0f},
        {0x1399, 0x14aa, 0x1d7e},
        {0x0763, 0x1349, 0x16bb},
        {0x0aa5, 0x0d06, 0x0f87},
        {0x0d46, 0x143a, 0x197c},
        {0x00a0, 0x1a5d, 0x1ebf},
        {0x0f07, 0x1239, 0x171b},
        {0x0211, 0x0fa7, 0x189c}
    },
    {
        {0x1369, 0x173b, 0x1e7f},
        {0x0391, 0x0432, 0x0f17},
        {0x0542, 0x06b3, 0x1038},
        {0x14ba, 0x164b, 0x1f6f},
        {0x02b1, 0x0552, 0x0db6},
        {0x0371, 0x0b65, 0x0c76},
        {0x0a35, 0x18bc, 0x1dbe},
        {0x0b15, 0x170b, 0x1f9f}
    },
    {
        {0x0060, 0x0c16, 0x0e77},
        {0x0b85, 0x156a, 0x1b2d},
        {0x09a4, 0x1168, 0x1219},
        {0x0150, 0x0d36, 0x1188},
        {0x0703, 0x0f97, 0x1c2e},
        {0x1379, 0x144a, 0x1f8f},
        {0x0653, 0x0984, 0x198c},
        {0x1329, 0x1b6d, 0x1d6e}
    },
    {
        {0x0412, 0x11b8, 0x150a},
        {0x0110, 0x1d3e, 0x1f2f},
        {0x0c96, 0x0f67, 0x17ab},
        {0x0251, 0x1128, 0x179b},
        {0x0130, 0x0bb5, 0x193c},
        {0x0170, 0x0331, 0x0a05},
        {0x0572, 0x0944, 0x1e1f},
        {0x0120, 0x141a, 0x1b8d}
    },
    {
        {0x0b75, 0x162b, 0x1b0d},
        {0x0874, 0x1259, 0x157a},
        {0x0341, 0x0d66, 0x1bbd},
        {0x0783, 0x1048, 0x192c},
        {0x0994, 0x11a8, 0x1d9e},
        {0x05a2, 0x1a3d, 0x1f5f},
        {0x0582, 0x0723, 0x1008},
        {0x09b4, 0x0e57, 0x194c}
    },
    {
        {0x0562, 0x0733, 0x1158},
        {0x0da6, 0x0e37, 0x1a4d},
        {0x0773, 0x180c, 0x1d0e},
        {0x1309, 0x159a, 0x1b1d},
        {0x03a1, 0x0a45, 0x1bad},
        {0x0000, 0x1c5e, 0x1eaf},
        {0x0361, 0x0402, 0x165b},
        {0x0201, 0x0814, 0x12a9}
    }
};
constexpr uint32_t C_WRITE_core_time_shift = 0;
constexpr uint32_t C_WRITE_core_time_mask = 15u;
constexpr uint32_t C_WRITE_core_bank_shift = 4;
constexpr uint32_t C_WRITE_core_bank_mask = 15u;
constexpr uint32_t C_WRITE_core_noc_shift = 8;
constexpr uint32_t C_WRITE_core_noc_mask = 1u;
constexpr uint32_t C_WRITE_core_slot_ordinal_shift = 9;
constexpr uint32_t C_WRITE_core_slot_ordinal_mask = 15u;

FORCE_INLINE uint32_t C_WRITE_core_packed_at(const uint32_t y, const uint32_t x, const uint32_t chunk_idx) {
    return static_cast<uint32_t>(C_WRITE_core_packed[y][x][chunk_idx]);
}
FORCE_INLINE uint32_t C_WRITE_core_time(const uint32_t packed) {
    return (packed >> C_WRITE_core_time_shift) & C_WRITE_core_time_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_bank(const uint32_t packed) {
    return (packed >> C_WRITE_core_bank_shift) & C_WRITE_core_bank_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_noc(const uint32_t packed) {
    return (packed >> C_WRITE_core_noc_shift) & C_WRITE_core_noc_mask;
}
FORCE_INLINE uint32_t C_WRITE_core_slot_ordinal(const uint32_t packed) {
    return (packed >> C_WRITE_core_slot_ordinal_shift) & C_WRITE_core_slot_ordinal_mask;
}
